Repository CMPUT301F24iconic/iconic-RaffleEvent, pull requests merged in 2024-11, with the labels that each got.

#65 Zhiyuan
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/iconic_raffleevent/controller/EventController.java
  app/src/main/java/com/example/iconic_raffleevent/controller/FirebaseAttendee.java
  app/src/main/java/com/example/iconic_raffleevent/model/Event.java
  app/src/main/java/com/example/iconic_raffleevent/view/QRScannerActivity.java
Labels: enhancement

#78 ensure that the methods addUser, setWinNotificationsEnabled, and setLoseNotificationsEnabled are correctly defined in UserController.java
  app/build.gradle.kts
  app/src/main/java/com/example/iconic_raffleevent/controller/EventController.java
  app/src/main/java/com/example/iconic_raffleevent/controller/FirebaseAttendee.java
  app/src/main/java/com/example/iconic_raffleevent/controller/UserController.java
  app/src/main/java/com/example/iconic_raffleevent/view/EventDetailsActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/MainActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/QRScannerActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/UserControllerViewModel.java
  app/src/main/res/layout/activity_qr_scanner.xml
Labels: enhancement

#85 Zhiyuan2
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  build.gradle.kts
Labels: enhancement

#87 fix notification pref button logics, link noti buttons in top nav bar
  app/src/main/java/com/example/iconic_raffleevent/view/CreateEventActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/CreateFacilityActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/EventDetailsActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/EventListActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/MapActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/NotificationSettingsActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/NotificationsActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  app/src/main/res/drawable/settings_icon.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_notification_settings.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/notification_top_navbar.xml
  app/src/main/res/layout/top_navbar.xml
  docs/uml-diagrams/umlproject301_raffleevent.drawio
Labels: enhancement

#103 enable the cancel button to return the event list page, the gallery button to access the gallery from the cell phone and turn on or off the flashlight from the phone by pressing the icon for qr scanner activity
  app/src/main/java/com/example/iconic_raffleevent/view/QRScannerActivity.java
  app/src/main/res/drawable/ic_flashlight_on.xml
  app/src/main/res/layout/activity_qr_scanner.xml
  build.gradle.kts
Labels: enhancement, risk: low

#104 Zhiyuan
  app/build.gradle.kts
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/QRScannerActivity.java
  app/src/main/res/layout/activity_profile.xml
  gradle/libs.versions.toml
Labels: enhancement

#108 Zhiyuan
  app/build.gradle.kts
  app/src/main/java/com/example/iconic_raffleevent/controller/UserController.java
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/QRScannerActivity.java
  app/src/main/res/drawable/scanning_wave_background.xml
  app/src/main/res/layout/activity_qr_scanner.xml
  gradle/libs.versions.toml
Labels: enhancement

#110 when we upload the poster from create event, we should have a preview dialogue for the poster before we save the event
  app/src/main/java/com/example/iconic_raffleevent/view/CreateEventActivity.java
  app/src/main/res/layout/activity_create_event.xml
  gradle/libs.versions.toml
Labels: enhancement

#117 fix open qr scanner bug
  app/src/main/res/layout/activity_qr_scanner.xml
Labels: enhancement

#123 Added more useful but useless Activity test java
  app/src/main/java/com/example/iconic_raffleevent/BitmapLuminanceSource.java
  app/src/main/java/com/example/iconic_raffleevent/view/ConfirmedListActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/CreateEventActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/CreateFacilityActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/DeclinedListActivity.java
  app/src/main/java/com/example/iconic_raffleevent/view/DisplayQRCodeActivity.java
  app/src/test/java/com/example/iconic_raffleevent/ConfirmedListActivityTest.java
  app/src/test/java/com/example/iconic_raffleevent/CreateEventActivityTest.java
  app/src/test/java/com/example/iconic_raffleevent/CreateFacilityActivityTest.java
  app/src/test/java/com/example/iconic_raffleevent/DeclinedListActivityTest.java
  app/src/test/java/com/example/iconic_raffleevent/DisplayQRCodeActivityTest.java
  app/src/test/java/com/example/iconic_raffleevent/DrawerHelperTest.java
  app/src/test/java/com/example/iconic_raffleevent/EventAdapterTest.java
  gradle.properties
Labels: documentation

#129 The remove photo button is hidden initially if the user has no profile photo The button appears when a user uploads a photo The button is hidden again when the photo is removed The default avatar is shown when no photo is uploaded or after a photo is removed
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
  gradle/libs.versions.toml
Labels: enhancement

#131 added UI test for profile and passed correctly
  app/build.gradle.kts
  app/src/androidTest/java/com/example/iconic_raffleevent/EventTransitionsTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/FirebaseControllerTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ProfileActivityTest.java
  gradle/libs.versions.toml
Labels: enhancement

#133 updated UI again for profile and eventlist UII Test again
  app/src/androidTest/java/com/example/iconic_raffleevent/EventTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/FooterTransitionsTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/MenuDrawerTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ProfileActivityTest.java
Labels: enhancement

#134 added new waiting list test and deleted old waiting list test to pass UI testing
  app/src/androidTest/java/com/example/iconic_raffleevent/FirebaseControllerTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/WaitingListActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/WaitingListTest.java
Labels: enhancement

#135 Add adminEvent and notification QR view test watinglist UI tetsing
  app/build.gradle.kts
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminEventActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/DrawerHelperTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/NotificationAndQRTests.java
  app/src/androidTest/java/com/example/iconic_raffleevent/UserListTest.java
Labels: enhancement

#136 Zhiyuan
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminEventTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminFacilityActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminHubActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/EventListForAdminActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/FooterTransitionsTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/MenuDrawerTest.java
  app/src/main/java/com/example/iconic_raffleevent/view/EventListForAdminActivity.java
Labels: enhancement

#138 add notificationSetting test, profile photo test and create event test UI
  app/src/androidTest/java/com/example/iconic_raffleevent/CreateEventActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/EventDetailsForAdminActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ManageEventActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/NotificationsUITest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ProfilePhotoTest.java
  app/src/main/java/com/example/iconic_raffleevent/view/ProfileActivity.java
Labels: enhancement

#143 modified the UI test again and add Admin image, profile and QR code testing
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminImageActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminProfileActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/AdminQRCodeActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/AvatarGeneratorTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/CreateEventActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/DeclinedListActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/DrawerHelperTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/EventDetailsForAdminActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/EventTransitionsTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/FooterTransitionsTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/InvitedListActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/MapActivityTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/NotificationAndQRTests.java
  app/src/androidTest/java/com/example/iconic_raffleevent/ProfilePhotoTest.java
  app/src/androidTest/java/com/example/iconic_raffleevent/WaitingListActivityTest.java
Labels: enhancement
